// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.0
// source: kurbhan.proto

package kurbhanv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"` // customer, admin, driver, etc
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_kurbhan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_kurbhan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProto) Reset() {
	*x = UserProto{}
	mi := &file_kurbhan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProto) ProtoMessage() {}

func (x *UserProto) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProto.ProtoReflect.Descriptor instead.
func (*UserProto) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{2}
}

func (x *UserProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProto) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserProto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProto) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User          *UserProto             `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_kurbhan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUser() *UserProto {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_kurbhan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_kurbhan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{5}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CalculateRateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	OriginVillageId      string                 `protobuf:"bytes,1,opt,name=origin_village_id,json=originVillageId,proto3" json:"origin_village_id,omitempty"`
	DestinationVillageId string                 `protobuf:"bytes,2,opt,name=destination_village_id,json=destinationVillageId,proto3" json:"destination_village_id,omitempty"`
	ActualWeightKg       float64                `protobuf:"fixed64,3,opt,name=actual_weight_kg,json=actualWeightKg,proto3" json:"actual_weight_kg,omitempty"`
	LengthCm             float64                `protobuf:"fixed64,4,opt,name=length_cm,json=lengthCm,proto3" json:"length_cm,omitempty"`
	WidthCm              float64                `protobuf:"fixed64,5,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	HeightCm             float64                `protobuf:"fixed64,6,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	VehicleType          string                 `protobuf:"bytes,7,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"` // mobil_box_kecil, mobil_box_sedang, mobil_box_besar
	ServiceType          string                 `protobuf:"bytes,8,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"` // reguler, cepat, sameday
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CalculateRateRequest) Reset() {
	*x = CalculateRateRequest{}
	mi := &file_kurbhan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRateRequest) ProtoMessage() {}

func (x *CalculateRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRateRequest.ProtoReflect.Descriptor instead.
func (*CalculateRateRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateRateRequest) GetOriginVillageId() string {
	if x != nil {
		return x.OriginVillageId
	}
	return ""
}

func (x *CalculateRateRequest) GetDestinationVillageId() string {
	if x != nil {
		return x.DestinationVillageId
	}
	return ""
}

func (x *CalculateRateRequest) GetActualWeightKg() float64 {
	if x != nil {
		return x.ActualWeightKg
	}
	return 0
}

func (x *CalculateRateRequest) GetLengthCm() float64 {
	if x != nil {
		return x.LengthCm
	}
	return 0
}

func (x *CalculateRateRequest) GetWidthCm() float64 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *CalculateRateRequest) GetHeightCm() float64 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

func (x *CalculateRateRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CalculateRateRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

type CalculateRateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	VolumetricWeightKg float64                `protobuf:"fixed64,1,opt,name=volumetric_weight_kg,json=volumetricWeightKg,proto3" json:"volumetric_weight_kg,omitempty"`
	ChargeableWeightKg float64                `protobuf:"fixed64,2,opt,name=chargeable_weight_kg,json=chargeableWeightKg,proto3" json:"chargeable_weight_kg,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	IsCrossIsland      bool                   `protobuf:"varint,4,opt,name=is_cross_island,json=isCrossIsland,proto3" json:"is_cross_island,omitempty"`
	EstimatedMinDays   string                 `protobuf:"bytes,5,opt,name=estimated_min_days,json=estimatedMinDays,proto3" json:"estimated_min_days,omitempty"`
	EstimatedMaxDays   string                 `protobuf:"bytes,6,opt,name=estimated_max_days,json=estimatedMaxDays,proto3" json:"estimated_max_days,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CalculateRateResponse) Reset() {
	*x = CalculateRateResponse{}
	mi := &file_kurbhan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateRateResponse) ProtoMessage() {}

func (x *CalculateRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateRateResponse.ProtoReflect.Descriptor instead.
func (*CalculateRateResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateRateResponse) GetVolumetricWeightKg() float64 {
	if x != nil {
		return x.VolumetricWeightKg
	}
	return 0
}

func (x *CalculateRateResponse) GetChargeableWeightKg() float64 {
	if x != nil {
		return x.ChargeableWeightKg
	}
	return 0
}

func (x *CalculateRateResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CalculateRateResponse) GetIsCrossIsland() bool {
	if x != nil {
		return x.IsCrossIsland
	}
	return false
}

func (x *CalculateRateResponse) GetEstimatedMinDays() string {
	if x != nil {
		return x.EstimatedMinDays
	}
	return ""
}

func (x *CalculateRateResponse) GetEstimatedMaxDays() string {
	if x != nil {
		return x.EstimatedMaxDays
	}
	return ""
}

type CreateShipmentRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SenderName           string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderAddress        string                 `protobuf:"bytes,3,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	SenderPhone          string                 `protobuf:"bytes,4,opt,name=sender_phone,json=senderPhone,proto3" json:"sender_phone,omitempty"`
	ReceiverName         string                 `protobuf:"bytes,5,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverAddress      string                 `protobuf:"bytes,6,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	ReceiverPhone        string                 `protobuf:"bytes,7,opt,name=receiver_phone,json=receiverPhone,proto3" json:"receiver_phone,omitempty"`
	OriginVillageId      string                 `protobuf:"bytes,8,opt,name=origin_village_id,json=originVillageId,proto3" json:"origin_village_id,omitempty"`
	DestinationVillageId string                 `protobuf:"bytes,9,opt,name=destination_village_id,json=destinationVillageId,proto3" json:"destination_village_id,omitempty"`
	WeightKg             float64                `protobuf:"fixed64,10,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	ServiceType          string                 `protobuf:"bytes,11,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TotalCost            float64                `protobuf:"fixed64,12,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_kurbhan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{8}
}

func (x *CreateShipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShipmentRequest) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *CreateShipmentRequest) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *CreateShipmentRequest) GetSenderPhone() string {
	if x != nil {
		return x.SenderPhone
	}
	return ""
}

func (x *CreateShipmentRequest) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *CreateShipmentRequest) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *CreateShipmentRequest) GetReceiverPhone() string {
	if x != nil {
		return x.ReceiverPhone
	}
	return ""
}

func (x *CreateShipmentRequest) GetOriginVillageId() string {
	if x != nil {
		return x.OriginVillageId
	}
	return ""
}

func (x *CreateShipmentRequest) GetDestinationVillageId() string {
	if x != nil {
		return x.DestinationVillageId
	}
	return ""
}

func (x *CreateShipmentRequest) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *CreateShipmentRequest) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *CreateShipmentRequest) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

type CreateShipmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId     string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShipmentResponse) Reset() {
	*x = CreateShipmentResponse{}
	mi := &file_kurbhan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentResponse) ProtoMessage() {}

func (x *CreateShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentResponse.ProtoReflect.Descriptor instead.
func (*CreateShipmentResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{9}
}

func (x *CreateShipmentResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *CreateShipmentResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *CreateShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateShipmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateShipmentStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location       string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShipmentStatusRequest) Reset() {
	*x = UpdateShipmentStatusRequest{}
	mi := &file_kurbhan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusRequest) ProtoMessage() {}

func (x *UpdateShipmentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateShipmentStatusRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateShipmentStatusRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateShipmentStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId     string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Success        bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateShipmentStatusResponse) Reset() {
	*x = UpdateShipmentStatusResponse{}
	mi := &file_kurbhan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateShipmentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShipmentStatusResponse) ProtoMessage() {}

func (x *UpdateShipmentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShipmentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateShipmentStatusResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateShipmentStatusResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateShipmentStatusResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *UpdateShipmentStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateShipmentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateShipmentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CancelShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelShipmentRequest) Reset() {
	*x = CancelShipmentRequest{}
	mi := &file_kurbhan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelShipmentRequest) ProtoMessage() {}

func (x *CancelShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelShipmentRequest.ProtoReflect.Descriptor instead.
func (*CancelShipmentRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{12}
}

func (x *CancelShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *CancelShipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ShipmentProto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TrackingNumber  string                 `protobuf:"bytes,2,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	SenderName      string                 `protobuf:"bytes,3,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	SenderAddress   string                 `protobuf:"bytes,4,opt,name=sender_address,json=senderAddress,proto3" json:"sender_address,omitempty"`
	ReceiverName    string                 `protobuf:"bytes,5,opt,name=receiver_name,json=receiverName,proto3" json:"receiver_name,omitempty"`
	ReceiverAddress string                 `protobuf:"bytes,6,opt,name=receiver_address,json=receiverAddress,proto3" json:"receiver_address,omitempty"`
	WeightKg        float64                `protobuf:"fixed64,7,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	ServiceType     string                 `protobuf:"bytes,8,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	TotalCost       float64                `protobuf:"fixed64,9,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ShipmentProto) Reset() {
	*x = ShipmentProto{}
	mi := &file_kurbhan_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentProto) ProtoMessage() {}

func (x *ShipmentProto) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentProto.ProtoReflect.Descriptor instead.
func (*ShipmentProto) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{13}
}

func (x *ShipmentProto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentProto) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentProto) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ShipmentProto) GetSenderAddress() string {
	if x != nil {
		return x.SenderAddress
	}
	return ""
}

func (x *ShipmentProto) GetReceiverName() string {
	if x != nil {
		return x.ReceiverName
	}
	return ""
}

func (x *ShipmentProto) GetReceiverAddress() string {
	if x != nil {
		return x.ReceiverAddress
	}
	return ""
}

func (x *ShipmentProto) GetWeightKg() float64 {
	if x != nil {
		return x.WeightKg
	}
	return 0
}

func (x *ShipmentProto) GetServiceType() string {
	if x != nil {
		return x.ServiceType
	}
	return ""
}

func (x *ShipmentProto) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *ShipmentProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TrackingHistoryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackingHistoryProto) Reset() {
	*x = TrackingHistoryProto{}
	mi := &file_kurbhan_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackingHistoryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackingHistoryProto) ProtoMessage() {}

func (x *TrackingHistoryProto) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackingHistoryProto.ProtoReflect.Descriptor instead.
func (*TrackingHistoryProto) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{14}
}

func (x *TrackingHistoryProto) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TrackingHistoryProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TrackingHistoryProto) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TrackingHistoryProto) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TrackShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TrackingNumber string                 `protobuf:"bytes,1,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrackShipmentRequest) Reset() {
	*x = TrackShipmentRequest{}
	mi := &file_kurbhan_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentRequest) ProtoMessage() {}

func (x *TrackShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentRequest.ProtoReflect.Descriptor instead.
func (*TrackShipmentRequest) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{15}
}

func (x *TrackShipmentRequest) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

type TrackShipmentResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Shipment      *ShipmentProto          `protobuf:"bytes,1,opt,name=shipment,proto3" json:"shipment,omitempty"`
	Histories     []*TrackingHistoryProto `protobuf:"bytes,2,rep,name=histories,proto3" json:"histories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackShipmentResponse) Reset() {
	*x = TrackShipmentResponse{}
	mi := &file_kurbhan_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackShipmentResponse) ProtoMessage() {}

func (x *TrackShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackShipmentResponse.ProtoReflect.Descriptor instead.
func (*TrackShipmentResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{16}
}

func (x *TrackShipmentResponse) GetShipment() *ShipmentProto {
	if x != nil {
		return x.Shipment
	}
	return nil
}

func (x *TrackShipmentResponse) GetHistories() []*TrackingHistoryProto {
	if x != nil {
		return x.Histories
	}
	return nil
}

type ShipmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShipmentResponse) Reset() {
	*x = ShipmentResponse{}
	mi := &file_kurbhan_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentResponse) ProtoMessage() {}

func (x *ShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kurbhan_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentResponse.ProtoReflect.Descriptor instead.
func (*ShipmentResponse) Descriptor() ([]byte, []int) {
	return file_kurbhan_proto_rawDescGZIP(), []int{17}
}

func (x *ShipmentResponse) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *ShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *ShipmentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_kurbhan_proto protoreflect.FileDescriptor

const file_kurbhan_proto_rawDesc = "" +
	"\n" +
	"\rkurbhan.proto\x12\n" +
	"kurbhan.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"b\n" +
	"\tUserProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"P\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12)\n" +
	"\x04user\x18\x02 \x01(\v2\x15.kurbhan.v1.UserProtoR\x04user\"E\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Q\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xbd\x02\n" +
	"\x14CalculateRateRequest\x12*\n" +
	"\x11origin_village_id\x18\x01 \x01(\tR\x0foriginVillageId\x124\n" +
	"\x16destination_village_id\x18\x02 \x01(\tR\x14destinationVillageId\x12(\n" +
	"\x10actual_weight_kg\x18\x03 \x01(\x01R\x0eactualWeightKg\x12\x1b\n" +
	"\tlength_cm\x18\x04 \x01(\x01R\blengthCm\x12\x19\n" +
	"\bwidth_cm\x18\x05 \x01(\x01R\awidthCm\x12\x1b\n" +
	"\theight_cm\x18\x06 \x01(\x01R\bheightCm\x12!\n" +
	"\fvehicle_type\x18\a \x01(\tR\vvehicleType\x12!\n" +
	"\fservice_type\x18\b \x01(\tR\vserviceType\"\xa0\x02\n" +
	"\x15CalculateRateResponse\x120\n" +
	"\x14volumetric_weight_kg\x18\x01 \x01(\x01R\x12volumetricWeightKg\x120\n" +
	"\x14chargeable_weight_kg\x18\x02 \x01(\x01R\x12chargeableWeightKg\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12&\n" +
	"\x0fis_cross_island\x18\x04 \x01(\bR\risCrossIsland\x12,\n" +
	"\x12estimated_min_days\x18\x05 \x01(\tR\x10estimatedMinDays\x12,\n" +
	"\x12estimated_max_days\x18\x06 \x01(\tR\x10estimatedMaxDays\"\xd3\x03\n" +
	"\x15CreateShipmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12%\n" +
	"\x0esender_address\x18\x03 \x01(\tR\rsenderAddress\x12!\n" +
	"\fsender_phone\x18\x04 \x01(\tR\vsenderPhone\x12#\n" +
	"\rreceiver_name\x18\x05 \x01(\tR\freceiverName\x12)\n" +
	"\x10receiver_address\x18\x06 \x01(\tR\x0freceiverAddress\x12%\n" +
	"\x0ereceiver_phone\x18\a \x01(\tR\rreceiverPhone\x12*\n" +
	"\x11origin_village_id\x18\b \x01(\tR\x0foriginVillageId\x124\n" +
	"\x16destination_village_id\x18\t \x01(\tR\x14destinationVillageId\x12\x1b\n" +
	"\tweight_kg\x18\n" +
	" \x01(\x01R\bweightKg\x12!\n" +
	"\fservice_type\x18\v \x01(\tR\vserviceType\x12\x1d\n" +
	"\n" +
	"total_cost\x18\f \x01(\x01R\ttotalCost\"\x94\x01\n" +
	"\x16CreateShipmentResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x1bUpdateShipmentStatusRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xb4\x01\n" +
	"\x1cUpdateShipmentStatusResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\"Q\n" +
	"\x15CancelShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xd7\x02\n" +
	"\rShipmentProto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0ftracking_number\x18\x02 \x01(\tR\x0etrackingNumber\x12\x1f\n" +
	"\vsender_name\x18\x03 \x01(\tR\n" +
	"senderName\x12%\n" +
	"\x0esender_address\x18\x04 \x01(\tR\rsenderAddress\x12#\n" +
	"\rreceiver_name\x18\x05 \x01(\tR\freceiverName\x12)\n" +
	"\x10receiver_address\x18\x06 \x01(\tR\x0freceiverAddress\x12\x1b\n" +
	"\tweight_kg\x18\a \x01(\x01R\bweightKg\x12!\n" +
	"\fservice_type\x18\b \x01(\tR\vserviceType\x12\x1d\n" +
	"\n" +
	"total_cost\x18\t \x01(\x01R\ttotalCost\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\"\x8a\x01\n" +
	"\x14TrackingHistoryProto\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"?\n" +
	"\x14TrackShipmentRequest\x12'\n" +
	"\x0ftracking_number\x18\x01 \x01(\tR\x0etrackingNumber\"\x8e\x01\n" +
	"\x15TrackShipmentResponse\x125\n" +
	"\bshipment\x18\x01 \x01(\v2\x19.kurbhan.v1.ShipmentProtoR\bshipment\x12>\n" +
	"\thistories\x18\x02 \x03(\v2 .kurbhan.v1.TrackingHistoryProtoR\thistories\"\xa7\x01\n" +
	"\x10ShipmentResponse\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\x92\x01\n" +
	"\vAuthService\x12E\n" +
	"\bRegister\x12\x1b.kurbhan.v1.RegisterRequest\x1a\x1c.kurbhan.v1.RegisterResponse\x12<\n" +
	"\x05Login\x12\x18.kurbhan.v1.LoginRequest\x1a\x19.kurbhan.v1.LoginResponse2c\n" +
	"\vRateService\x12T\n" +
	"\rCalculateRate\x12 .kurbhan.v1.CalculateRateRequest\x1a!.kurbhan.v1.CalculateRateResponse2\xfe\x02\n" +
	"\x0fShipmentService\x12W\n" +
	"\x0eCreateShipment\x12!.kurbhan.v1.CreateShipmentRequest\x1a\".kurbhan.v1.CreateShipmentResponse\x12i\n" +
	"\x14UpdateShipmentStatus\x12'.kurbhan.v1.UpdateShipmentStatusRequest\x1a(.kurbhan.v1.UpdateShipmentStatusResponse\x12Q\n" +
	"\x0eCancelShipment\x12!.kurbhan.v1.CancelShipmentRequest\x1a\x1c.kurbhan.v1.ShipmentResponse\x12T\n" +
	"\rTrackShipment\x12 .kurbhan.v1.TrackShipmentRequest\x1a!.kurbhan.v1.TrackShipmentResponseB\x1aZ\x18kurbhan/gen/v1;kurbhanv1b\x06proto3"

var (
	file_kurbhan_proto_rawDescOnce sync.Once
	file_kurbhan_proto_rawDescData []byte
)

func file_kurbhan_proto_rawDescGZIP() []byte {
	file_kurbhan_proto_rawDescOnce.Do(func() {
		file_kurbhan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kurbhan_proto_rawDesc), len(file_kurbhan_proto_rawDesc)))
	})
	return file_kurbhan_proto_rawDescData
}

var file_kurbhan_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_kurbhan_proto_goTypes = []any{
	(*RegisterRequest)(nil),              // 0: kurbhan.v1.RegisterRequest
	(*LoginRequest)(nil),                 // 1: kurbhan.v1.LoginRequest
	(*UserProto)(nil),                    // 2: kurbhan.v1.UserProto
	(*LoginResponse)(nil),                // 3: kurbhan.v1.LoginResponse
	(*RegisterResponse)(nil),             // 4: kurbhan.v1.RegisterResponse
	(*AuthResponse)(nil),                 // 5: kurbhan.v1.AuthResponse
	(*CalculateRateRequest)(nil),         // 6: kurbhan.v1.CalculateRateRequest
	(*CalculateRateResponse)(nil),        // 7: kurbhan.v1.CalculateRateResponse
	(*CreateShipmentRequest)(nil),        // 8: kurbhan.v1.CreateShipmentRequest
	(*CreateShipmentResponse)(nil),       // 9: kurbhan.v1.CreateShipmentResponse
	(*UpdateShipmentStatusRequest)(nil),  // 10: kurbhan.v1.UpdateShipmentStatusRequest
	(*UpdateShipmentStatusResponse)(nil), // 11: kurbhan.v1.UpdateShipmentStatusResponse
	(*CancelShipmentRequest)(nil),        // 12: kurbhan.v1.CancelShipmentRequest
	(*ShipmentProto)(nil),                // 13: kurbhan.v1.ShipmentProto
	(*TrackingHistoryProto)(nil),         // 14: kurbhan.v1.TrackingHistoryProto
	(*TrackShipmentRequest)(nil),         // 15: kurbhan.v1.TrackShipmentRequest
	(*TrackShipmentResponse)(nil),        // 16: kurbhan.v1.TrackShipmentResponse
	(*ShipmentResponse)(nil),             // 17: kurbhan.v1.ShipmentResponse
	(*timestamppb.Timestamp)(nil),        // 18: google.protobuf.Timestamp
}
var file_kurbhan_proto_depIdxs = []int32{
	2,  // 0: kurbhan.v1.LoginResponse.user:type_name -> kurbhan.v1.UserProto
	13, // 1: kurbhan.v1.TrackShipmentResponse.shipment:type_name -> kurbhan.v1.ShipmentProto
	14, // 2: kurbhan.v1.TrackShipmentResponse.histories:type_name -> kurbhan.v1.TrackingHistoryProto
	18, // 3: kurbhan.v1.ShipmentResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: kurbhan.v1.AuthService.Register:input_type -> kurbhan.v1.RegisterRequest
	1,  // 5: kurbhan.v1.AuthService.Login:input_type -> kurbhan.v1.LoginRequest
	6,  // 6: kurbhan.v1.RateService.CalculateRate:input_type -> kurbhan.v1.CalculateRateRequest
	8,  // 7: kurbhan.v1.ShipmentService.CreateShipment:input_type -> kurbhan.v1.CreateShipmentRequest
	10, // 8: kurbhan.v1.ShipmentService.UpdateShipmentStatus:input_type -> kurbhan.v1.UpdateShipmentStatusRequest
	12, // 9: kurbhan.v1.ShipmentService.CancelShipment:input_type -> kurbhan.v1.CancelShipmentRequest
	15, // 10: kurbhan.v1.ShipmentService.TrackShipment:input_type -> kurbhan.v1.TrackShipmentRequest
	4,  // 11: kurbhan.v1.AuthService.Register:output_type -> kurbhan.v1.RegisterResponse
	3,  // 12: kurbhan.v1.AuthService.Login:output_type -> kurbhan.v1.LoginResponse
	7,  // 13: kurbhan.v1.RateService.CalculateRate:output_type -> kurbhan.v1.CalculateRateResponse
	9,  // 14: kurbhan.v1.ShipmentService.CreateShipment:output_type -> kurbhan.v1.CreateShipmentResponse
	11, // 15: kurbhan.v1.ShipmentService.UpdateShipmentStatus:output_type -> kurbhan.v1.UpdateShipmentStatusResponse
	17, // 16: kurbhan.v1.ShipmentService.CancelShipment:output_type -> kurbhan.v1.ShipmentResponse
	16, // 17: kurbhan.v1.ShipmentService.TrackShipment:output_type -> kurbhan.v1.TrackShipmentResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_kurbhan_proto_init() }
func file_kurbhan_proto_init() {
	if File_kurbhan_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kurbhan_proto_rawDesc), len(file_kurbhan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_kurbhan_proto_goTypes,
		DependencyIndexes: file_kurbhan_proto_depIdxs,
		MessageInfos:      file_kurbhan_proto_msgTypes,
	}.Build()
	File_kurbhan_proto = out.File
	file_kurbhan_proto_goTypes = nil
	file_kurbhan_proto_depIdxs = nil
}
