/**
 * @fileoverview gRPC-Web generated client stub for kurbhan.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.1.1
// 	protoc              v7.35.0
// source: kurbhan.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as kurbhan_pb from './kurbhan_pb'; // proto import: "kurbhan.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.RegisterRequest,
    kurbhan_pb.RegisterResponse,
    (request: kurbhan_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.RegisterResponse>;

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.RegisterResponse>;

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.LoginRequest,
    kurbhan_pb.LoginResponse,
    (request: kurbhan_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.LoginResponse.deserializeBinary
  );

  login(
    request: kurbhan_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.LoginResponse>;

  login(
    request: kurbhan_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.LoginResponse>;

  login(
    request: kurbhan_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

}

export class RateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCalculateRate = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.RateService/CalculateRate',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CalculateRateRequest,
    kurbhan_pb.CalculateRateResponse,
    (request: kurbhan_pb.CalculateRateRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CalculateRateResponse.deserializeBinary
  );

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CalculateRateResponse>;

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CalculateRateResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CalculateRateResponse>;

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CalculateRateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.RateService/CalculateRate',
        request,
        metadata || {},
        this.methodDescriptorCalculateRate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.RateService/CalculateRate',
    request,
    metadata || {},
    this.methodDescriptorCalculateRate);
  }

}

export class ShipmentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CreateShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CreateShipmentRequest,
    kurbhan_pb.CreateShipmentResponse,
    (request: kurbhan_pb.CreateShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CreateShipmentResponse.deserializeBinary
  );

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CreateShipmentResponse>;

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreateShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CreateShipmentResponse>;

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreateShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CreateShipment',
        request,
        metadata || {},
        this.methodDescriptorCreateShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CreateShipment',
    request,
    metadata || {},
    this.methodDescriptorCreateShipment);
  }

  methodDescriptorUpdateShipmentStatus = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.UpdateShipmentStatusRequest,
    kurbhan_pb.UpdateShipmentStatusResponse,
    (request: kurbhan_pb.UpdateShipmentStatusRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.UpdateShipmentStatusResponse.deserializeBinary
  );

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.UpdateShipmentStatusResponse>;

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateShipmentStatusResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.UpdateShipmentStatusResponse>;

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateShipmentStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
        request,
        metadata || {},
        this.methodDescriptorUpdateShipmentStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
    request,
    metadata || {},
    this.methodDescriptorUpdateShipmentStatus);
  }

  methodDescriptorCancelShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CancelShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CancelShipmentRequest,
    kurbhan_pb.ShipmentResponse,
    (request: kurbhan_pb.CancelShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.ShipmentResponse.deserializeBinary
  );

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.ShipmentResponse>;

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.ShipmentResponse>;

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CancelShipment',
        request,
        metadata || {},
        this.methodDescriptorCancelShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CancelShipment',
    request,
    metadata || {},
    this.methodDescriptorCancelShipment);
  }

  methodDescriptorTrackShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/TrackShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.TrackShipmentRequest,
    kurbhan_pb.TrackShipmentResponse,
    (request: kurbhan_pb.TrackShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.TrackShipmentResponse.deserializeBinary
  );

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.TrackShipmentResponse>;

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.TrackShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.TrackShipmentResponse>;

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.TrackShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/TrackShipment',
        request,
        metadata || {},
        this.methodDescriptorTrackShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/TrackShipment',
    request,
    metadata || {},
    this.methodDescriptorTrackShipment);
  }

  methodDescriptorGetDriverAssignedShipments = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/GetDriverAssignedShipments',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.GetDriverShipmentsRequest,
    kurbhan_pb.GetDriverShipmentsResponse,
    (request: kurbhan_pb.GetDriverShipmentsRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.GetDriverShipmentsResponse.deserializeBinary
  );

  getDriverAssignedShipments(
    request: kurbhan_pb.GetDriverShipmentsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.GetDriverShipmentsResponse>;

  getDriverAssignedShipments(
    request: kurbhan_pb.GetDriverShipmentsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetDriverShipmentsResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.GetDriverShipmentsResponse>;

  getDriverAssignedShipments(
    request: kurbhan_pb.GetDriverShipmentsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetDriverShipmentsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/GetDriverAssignedShipments',
        request,
        metadata || {},
        this.methodDescriptorGetDriverAssignedShipments,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/GetDriverAssignedShipments',
    request,
    metadata || {},
    this.methodDescriptorGetDriverAssignedShipments);
  }

  methodDescriptorAcceptShipmentJob = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/AcceptShipmentJob',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.AcceptJobRequest,
    kurbhan_pb.AcceptJobResponse,
    (request: kurbhan_pb.AcceptJobRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.AcceptJobResponse.deserializeBinary
  );

  acceptShipmentJob(
    request: kurbhan_pb.AcceptJobRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.AcceptJobResponse>;

  acceptShipmentJob(
    request: kurbhan_pb.AcceptJobRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.AcceptJobResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.AcceptJobResponse>;

  acceptShipmentJob(
    request: kurbhan_pb.AcceptJobRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.AcceptJobResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/AcceptShipmentJob',
        request,
        metadata || {},
        this.methodDescriptorAcceptShipmentJob,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/AcceptShipmentJob',
    request,
    metadata || {},
    this.methodDescriptorAcceptShipmentJob);
  }

  methodDescriptorUpdateDriverLocation = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/UpdateDriverLocation',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.UpdateLocationRequest,
    kurbhan_pb.UpdateLocationResponse,
    (request: kurbhan_pb.UpdateLocationRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.UpdateLocationResponse.deserializeBinary
  );

  updateDriverLocation(
    request: kurbhan_pb.UpdateLocationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.UpdateLocationResponse>;

  updateDriverLocation(
    request: kurbhan_pb.UpdateLocationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateLocationResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.UpdateLocationResponse>;

  updateDriverLocation(
    request: kurbhan_pb.UpdateLocationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateLocationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/UpdateDriverLocation',
        request,
        metadata || {},
        this.methodDescriptorUpdateDriverLocation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/UpdateDriverLocation',
    request,
    metadata || {},
    this.methodDescriptorUpdateDriverLocation);
  }

  methodDescriptorCompleteDelivery = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CompleteDelivery',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CompleteDeliveryRequest,
    kurbhan_pb.CompleteDeliveryResponse,
    (request: kurbhan_pb.CompleteDeliveryRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CompleteDeliveryResponse.deserializeBinary
  );

  completeDelivery(
    request: kurbhan_pb.CompleteDeliveryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CompleteDeliveryResponse>;

  completeDelivery(
    request: kurbhan_pb.CompleteDeliveryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CompleteDeliveryResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CompleteDeliveryResponse>;

  completeDelivery(
    request: kurbhan_pb.CompleteDeliveryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CompleteDeliveryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CompleteDelivery',
        request,
        metadata || {},
        this.methodDescriptorCompleteDelivery,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CompleteDelivery',
    request,
    metadata || {},
    this.methodDescriptorCompleteDelivery);
  }

  methodDescriptorCollectCODPayment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CollectCODPayment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CollectCODRequest,
    kurbhan_pb.CollectCODResponse,
    (request: kurbhan_pb.CollectCODRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CollectCODResponse.deserializeBinary
  );

  collectCODPayment(
    request: kurbhan_pb.CollectCODRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CollectCODResponse>;

  collectCODPayment(
    request: kurbhan_pb.CollectCODRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CollectCODResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CollectCODResponse>;

  collectCODPayment(
    request: kurbhan_pb.CollectCODRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CollectCODResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CollectCODPayment',
        request,
        metadata || {},
        this.methodDescriptorCollectCODPayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CollectCODPayment',
    request,
    metadata || {},
    this.methodDescriptorCollectCODPayment);
  }

}

export class PaymentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreatePayment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.PaymentService/CreatePayment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CreatePaymentRequest,
    kurbhan_pb.CreatePaymentResponse,
    (request: kurbhan_pb.CreatePaymentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CreatePaymentResponse.deserializeBinary
  );

  createPayment(
    request: kurbhan_pb.CreatePaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CreatePaymentResponse>;

  createPayment(
    request: kurbhan_pb.CreatePaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreatePaymentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CreatePaymentResponse>;

  createPayment(
    request: kurbhan_pb.CreatePaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreatePaymentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.PaymentService/CreatePayment',
        request,
        metadata || {},
        this.methodDescriptorCreatePayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.PaymentService/CreatePayment',
    request,
    metadata || {},
    this.methodDescriptorCreatePayment);
  }

  methodDescriptorGetPaymentStatus = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.PaymentService/GetPaymentStatus',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.GetPaymentStatusRequest,
    kurbhan_pb.GetPaymentStatusResponse,
    (request: kurbhan_pb.GetPaymentStatusRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.GetPaymentStatusResponse.deserializeBinary
  );

  getPaymentStatus(
    request: kurbhan_pb.GetPaymentStatusRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.GetPaymentStatusResponse>;

  getPaymentStatus(
    request: kurbhan_pb.GetPaymentStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetPaymentStatusResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.GetPaymentStatusResponse>;

  getPaymentStatus(
    request: kurbhan_pb.GetPaymentStatusRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetPaymentStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.PaymentService/GetPaymentStatus',
        request,
        metadata || {},
        this.methodDescriptorGetPaymentStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.PaymentService/GetPaymentStatus',
    request,
    metadata || {},
    this.methodDescriptorGetPaymentStatus);
  }

  methodDescriptorConfirmPayment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.PaymentService/ConfirmPayment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.ConfirmPaymentRequest,
    kurbhan_pb.ConfirmPaymentResponse,
    (request: kurbhan_pb.ConfirmPaymentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.ConfirmPaymentResponse.deserializeBinary
  );

  confirmPayment(
    request: kurbhan_pb.ConfirmPaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.ConfirmPaymentResponse>;

  confirmPayment(
    request: kurbhan_pb.ConfirmPaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ConfirmPaymentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.ConfirmPaymentResponse>;

  confirmPayment(
    request: kurbhan_pb.ConfirmPaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ConfirmPaymentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.PaymentService/ConfirmPayment',
        request,
        metadata || {},
        this.methodDescriptorConfirmPayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.PaymentService/ConfirmPayment',
    request,
    metadata || {},
    this.methodDescriptorConfirmPayment);
  }

  methodDescriptorProcessVATransaction = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.PaymentService/ProcessVATransaction',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.ProcessVATransactionRequest,
    kurbhan_pb.ProcessVATransactionResponse,
    (request: kurbhan_pb.ProcessVATransactionRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.ProcessVATransactionResponse.deserializeBinary
  );

  processVATransaction(
    request: kurbhan_pb.ProcessVATransactionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.ProcessVATransactionResponse>;

  processVATransaction(
    request: kurbhan_pb.ProcessVATransactionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ProcessVATransactionResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.ProcessVATransactionResponse>;

  processVATransaction(
    request: kurbhan_pb.ProcessVATransactionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ProcessVATransactionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.PaymentService/ProcessVATransaction',
        request,
        metadata || {},
        this.methodDescriptorProcessVATransaction,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.PaymentService/ProcessVATransaction',
    request,
    metadata || {},
    this.methodDescriptorProcessVATransaction);
  }

  methodDescriptorGetPaymentMethods = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.PaymentService/GetPaymentMethods',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.GetPaymentMethodsRequest,
    kurbhan_pb.GetPaymentMethodsResponse,
    (request: kurbhan_pb.GetPaymentMethodsRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.GetPaymentMethodsResponse.deserializeBinary
  );

  getPaymentMethods(
    request: kurbhan_pb.GetPaymentMethodsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.GetPaymentMethodsResponse>;

  getPaymentMethods(
    request: kurbhan_pb.GetPaymentMethodsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetPaymentMethodsResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.GetPaymentMethodsResponse>;

  getPaymentMethods(
    request: kurbhan_pb.GetPaymentMethodsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.GetPaymentMethodsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.PaymentService/GetPaymentMethods',
        request,
        metadata || {},
        this.methodDescriptorGetPaymentMethods,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.PaymentService/GetPaymentMethods',
    request,
    metadata || {},
    this.methodDescriptorGetPaymentMethods);
  }

}

