/**
 * @fileoverview gRPC-Web generated client stub for kurbhan.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.1.1
// 	protoc              v7.36.0
// source: kurbhan.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as kurbhan_pb from './kurbhan_pb'; // proto import: "kurbhan.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.RegisterRequest,
    kurbhan_pb.RegisterResponse,
    (request: kurbhan_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.RegisterResponse>;

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.RegisterResponse>;

  register(
    request: kurbhan_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.LoginRequest,
    kurbhan_pb.LoginResponse,
    (request: kurbhan_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.LoginResponse.deserializeBinary
  );

  login(
    request: kurbhan_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.LoginResponse>;

  login(
    request: kurbhan_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.LoginResponse>;

  login(
    request: kurbhan_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

}

export class RateServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCalculateRate = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.RateService/CalculateRate',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CalculateRateRequest,
    kurbhan_pb.CalculateRateResponse,
    (request: kurbhan_pb.CalculateRateRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CalculateRateResponse.deserializeBinary
  );

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CalculateRateResponse>;

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CalculateRateResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CalculateRateResponse>;

  calculateRate(
    request: kurbhan_pb.CalculateRateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CalculateRateResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.RateService/CalculateRate',
        request,
        metadata || {},
        this.methodDescriptorCalculateRate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.RateService/CalculateRate',
    request,
    metadata || {},
    this.methodDescriptorCalculateRate);
  }

}

export class ShipmentServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CreateShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CreateShipmentRequest,
    kurbhan_pb.CreateShipmentResponse,
    (request: kurbhan_pb.CreateShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.CreateShipmentResponse.deserializeBinary
  );

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.CreateShipmentResponse>;

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreateShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.CreateShipmentResponse>;

  createShipment(
    request: kurbhan_pb.CreateShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.CreateShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CreateShipment',
        request,
        metadata || {},
        this.methodDescriptorCreateShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CreateShipment',
    request,
    metadata || {},
    this.methodDescriptorCreateShipment);
  }

  methodDescriptorUpdateShipmentStatus = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.UpdateShipmentStatusRequest,
    kurbhan_pb.UpdateShipmentStatusResponse,
    (request: kurbhan_pb.UpdateShipmentStatusRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.UpdateShipmentStatusResponse.deserializeBinary
  );

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.UpdateShipmentStatusResponse>;

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateShipmentStatusResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.UpdateShipmentStatusResponse>;

  updateShipmentStatus(
    request: kurbhan_pb.UpdateShipmentStatusRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.UpdateShipmentStatusResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
        request,
        metadata || {},
        this.methodDescriptorUpdateShipmentStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/UpdateShipmentStatus',
    request,
    metadata || {},
    this.methodDescriptorUpdateShipmentStatus);
  }

  methodDescriptorCancelShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/CancelShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.CancelShipmentRequest,
    kurbhan_pb.ShipmentResponse,
    (request: kurbhan_pb.CancelShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.ShipmentResponse.deserializeBinary
  );

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.ShipmentResponse>;

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.ShipmentResponse>;

  cancelShipment(
    request: kurbhan_pb.CancelShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.ShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/CancelShipment',
        request,
        metadata || {},
        this.methodDescriptorCancelShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/CancelShipment',
    request,
    metadata || {},
    this.methodDescriptorCancelShipment);
  }

  methodDescriptorTrackShipment = new grpcWeb.MethodDescriptor(
    '/kurbhan.v1.ShipmentService/TrackShipment',
    grpcWeb.MethodType.UNARY,
    kurbhan_pb.TrackShipmentRequest,
    kurbhan_pb.TrackShipmentResponse,
    (request: kurbhan_pb.TrackShipmentRequest) => {
      return request.serializeBinary();
    },
    kurbhan_pb.TrackShipmentResponse.deserializeBinary
  );

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<kurbhan_pb.TrackShipmentResponse>;

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: kurbhan_pb.TrackShipmentResponse) => void): grpcWeb.ClientReadableStream<kurbhan_pb.TrackShipmentResponse>;

  trackShipment(
    request: kurbhan_pb.TrackShipmentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: kurbhan_pb.TrackShipmentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/kurbhan.v1.ShipmentService/TrackShipment',
        request,
        metadata || {},
        this.methodDescriptorTrackShipment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/kurbhan.v1.ShipmentService/TrackShipment',
    request,
    metadata || {},
    this.methodDescriptorTrackShipment);
  }

}

